name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Generate Quarto Documentation 
        uses: fastai/workflows/quarto-ghp@master
