# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tjutils',
                'doc_host': 'https://tjpalanca.github.io',
                'git_url': 'https://github.com/tjpalanca/tjutils',
                'lib_path': 'tjutils'},
  'syms': {'tjutils.nbdev': {'tjutils.nbdev.export': ('01-nbdev.html#export', 'tjutils/nbdev.py')}}}