# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tjutils-py',
                'doc_host': 'https://tjpalanca.github.io',
                'git_url': 'https://github.com/tjpalanca/tjutils-py',
                'lib_path': 'tjutils'},
  'syms': {'tjutils.nbdev': {'tjutils.nbdev.sync': ('01-nbdev.html#sync', 'tjutils/nbdev.py')}}}