# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tjutils-py',
                'doc_host': 'https://tjpalanca.com',
                'git_url': 'https://github.com/tjpalanca/tjutils-py.git',
                'lib_path': 'tjutils'},
  'syms': { 'tjutils.nbdev': { 'tjutils.nbdev._get_classifier_value': ('01-nbdev.html#_get_classifier_value', 'tjutils/nbdev.py'),
                               'tjutils.nbdev.export': ('01-nbdev.html#export', 'tjutils/nbdev.py'),
                               'tjutils.nbdev.version': ('01-nbdev.html#version', 'tjutils/nbdev.py')}}}