# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/02-terraform.ipynb.

# %% auto 0
__all__ = ['github_actions']

# %% ../notebooks/02-terraform.ipynb 1
from fastcore.script import call_parse
from .utils import copy_template

# %% ../notebooks/02-terraform.ipynb 2
@call_parse
def github_actions():
    "Add GitHub Actions workflow for planning and applying with Terraform"
    copy_template(
        "terraform/github_actions/tf_deploy.yml", ".github/workflows/tf_deploy.yml"
    )
